name: CI Linux

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '!**/linux_ci.yml'
      - '**.csproj'
      - '**.csproj.old'
      - '**.csproj.old.1'
      - '**.godot'
      - '**.uid'
      - '**.import'
      - '**.tscn'
      - '**.gdshader'
      - '!cmd/tools/builders/**.v'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '!**/linux_ci.yml'
      - '**.csproj'
      - '**.csproj.old'
      - '**.csproj.old.1'
      - '**.godot'
      - '**.uid'
      - '**.import'
      - '**.tscn'
      - '**.gdshader'
      - '!cmd/tools/builders/**.v'

concurrency:
  group: linux-${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  tcc-linux:
    name: Test Runner
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup V language
        uses: sleeyax/vlang-action@v1
        with:
          version: latest
          
      - name: Run tests
        run: |
          cd ./test
          if v run main.v; then
            echo "✅ Tests passed successfully"
          else
            echo "❌ Tests failed: $?"
            exit 1
          fi
